apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: blue
  template:
    metadata:
      labels: 
        app: blue
    spec:
      containers:
        - name: blue-app
          image: hashicorp/http-echo
          args:
            - "-text=I am blue"


---

kind: Service
apiVersion: v1
metadata:
  name: blue-service
spec:
  selector:
    app: blue
  ports:
  - name: service0
    targetPort: 5678
    port: 8080
    protocol: TCP
  type: NodePort


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress-blue
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx # Use the Nginx ingress.
    #    nginx.ingress.kubernetes.io/canary: "true"
    #nginx.ingress.kubernetes.io/canary-weight: "75"
    kubernetes.io/elb.port: '80'    
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: blue-service
              port: 
                number: 8080
